## Include rules/common first as this file only defines input target
## functions and common configuration for the workflow
include: "rules/common.smk"


##############################
## Report
##############################
report: "report/workflow.rst"


# Allow users to fix the underlying OS via singularity.
container: "docker://continuumio/miniconda3"


rule all:
    input:
        unpack(all_input),


##############################
## Included rules
##############################
include: "rules/qc.smk"
include: "rules/krakenuniq.smk"
include: "rules/align.smk"
include: "rules/damage.smk"
include: "rules/malt.smk"
include: "rules/authentic.smk"
